### PR TITLE
Fix tests on Windows

### PR DESCRIPTION
**Pull request by jcs090218**
I have most of the tests fixed, but not the `lsp-dart-get-sdk-dir--flutter-project-test`.

Here is the backtrace:

```
Test lsp-dart-get-sdk-dir--flutter-project-test backtrace:
  signal(mock-error ((file-exists-p "/flutter-sdk/bin/cache/dart-sdk/"
  mock-verify-args(file-exists-p ("/flutter-sdk/bin/cache/dart-sdk/") 
  apply(mock-verify-args (file-exists-p ("/flutter-sdk/bin/cache/dart-
  mock-verify()
  #f(compiled-function () #<bytecode 0x1624b49f8b19cd36>)()
  mock-protect((lambda nil (if (not in-mocking) (error "Do not use `mo
  (with-mock (if (not in-mocking) (error "Do not use `mock' outside") 
  (let ((default-directory (file-truename "test/fixtures/flutter-proje
  (lsp-dart-test-from-flutter-project (if (not in-mocking) (error "Do 
  (let ((lexical-binding nil)) (lsp-dart-test-from-flutter-project (if
  (lambda nil (let ((lexical-binding nil)) (lsp-dart-test-from-flutter
  ...
  normal-top-level()
Test lsp-dart-get-sdk-dir--flutter-project-test condition:
    (mock-error
     (file-exists-p "/flutter-sdk/bin/cache/dart-sdk/")
     (file-exists-p "d:/"))
```

Not sure why it keeps returning `"d:/"`?

### CODE REVIEW

**Comment by ericdallo** [comment]
Yeah, pretty weird, it should return the project location, `d:/` doesn' t make sense

**Comment by jcs090218** [comment]
I think I would just need to wrap the execution outward with `let` operator.

This is ready to merge! Let me know if you need me to do something else with this PR! :)

**Comment by ericdallo** [comment]
Awesome! thank you!

**Comment by jcs090218** [comment]
Sorry, I think something went wrong with `eask`. I have reverted some changes; you can try rerun failed jobs and it should be working now! 😖

**Pull request merged**
