### PR TITLE
Bugfix flutter run

### PR DESCRIPTION
**Pull request by jheld**
Changes initially based on #215 but with the overall fix as requested in the comments. I couldn't find a way to continue to leverage `-lambda` so I opted to switch to regular `lambda -> let`.

### CODE REVIEW

**Comment by jheld** [comment]
@cheerio-pixel @Integral-tech , would be grateful for your feedback.

**Review by cheerio-pixel — APPROVED** [review]
LGTM

**Comment by Integral-Tech** [comment]
LGTM.

**Review by ericdallo — APPROVED** [review]
Thank you!

**Pull request merged**
