### PR TITLE
Attempt to resovle bad request

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by ericdallo** [comment]
Do we have these issues on lsp-mode?

**Comment by jcs090218** [comment]
> Do we have these issues on lsp-mode?

I think there was a similar issue in lsp-mode but not anymore.

**Comment by jcs090218** [comment]
Notice that Cask is no longer used for CI test due to the bad request from Emacs version 26.x on macOS. So I have made the test consistently using `windows-bootstrap.el`.

---

I am getting these test errors on windows test. Any idea?

```
8 unexpected results:
   FAILED  lsp-dart--flutter-repo-p--not-flutter-executable-test
   FAILED  lsp-dart--flutter-repo-p--true-test
   FAILED  lsp-dart--library-folders--extra-folder-and-lib-file-test
   FAILED  lsp-dart--library-folders--lib-file-test
   FAILED  lsp-dart--server-command--default-test
   FAILED  lsp-dart-dart-command--test
   FAILED  lsp-dart-flutter-command--test
   FAILED  lsp-dart-get-sdk-dir--flutter-project-test
```

**Comment by jcs090218** [comment]
I have restored the Cask installation. I think bad request is resolved by upstream, see https://github.com/cask/cask/issues/501.

Yet I cannot resolve the test errors from windows. 😕

**Comment by jcs090218** [comment]
Should resolved be #158

**Pull request closed without merging**
